[http]
scheme = "https"
host = "www.instagram.com"
[http.header]
ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"

[html]
shared_data_regex = "<script type=\"text/javascript\">window._sharedData = (.+?);</script>"

[postgres]
user = "fu"
pwd = "XPN]un"
db = "instagram"

[download]
folder = "/mnt/d/Download/instagram"

[worker]
concurrency = 20
